### ISSUE TITLE
自定义Retrofit请求缓存问题

### ISSUE THREAD

**Issue by qinicy** [xiaoyaoyou1212/XSnow#10]
自定义的Retrofit请求cacheKey每一次都是同一个，是不是需要每次请求手动设置不一样的cacheKey呢？

**Comment by xiaoyaoyou1212** [comment]
@qinicy 缓存key在请求时是要重新创建的，因为每个请求的key都不一样，框架中只是提供了一个默认的key

**Comment by qinicy** [comment]
能否在请求内部自动处理cacheKey？思路是把请求URL和参数组合起来作为cacheKey

**Comment by xiaoyaoyou1212** [comment]
@qinicy 这个我也考虑过，但是后面发现不好做，因为很多请求都会带动态参数，而动态参数不能作为缓存key，而参数哪些参数作为缓存key框架中是无法判定的，还是需要调用者告知，所以就没有统一处理，如果你有更好的方式也欢迎交流！
