### ISSUE TITLE
关于 BaseActivity 的问题

### ISSUE THREAD

**Issue by QuincySx** [xiaoyaoyou1212/XSnow#12]
我看到 BaseActivity 里面有个 mViews 用来缓存 View ，我感觉没什么用啊，在用的时候肯定是 find 完了存下来，你这样再存到 BaseActivity 里面缓存一遍，使用频度比较低吧，还是说有什么别的用途

**Comment by xiaoyaoyou1212** [comment]
@QuincySx 主要是为了防止重复find，如果已经find过就直接返回

**Comment by QuincySx** [comment]
好像也没有什么重复获取的需求吧，就这样的需求浪费内存好像没有太大意义吧

**Comment by xiaoyaoyou1212** [comment]
@QuincySx 刚刚看了下是没多大必要，我后面修改下
