### ISSUE TITLE
Glide可以更新到4.0了，有些项目还是用到了Glide4.0的

### ISSUE THREAD

**Issue by DaiFalin** [xiaoyaoyou1212/XSnow#13]

**Comment by xiaoyaoyou1212** [comment]
好，下个版本我更新下相关依赖库的版本。

**Comment by xiaoyaoyou1212** [comment]
@DaiFalin 我看了下最新的Glide改动还挺大的，如果我改成4.0后有些使用Glide3.x的项目使用上就会有问题，最后决定还是先保留，毕竟这个接口是开放的，可以定制不同的图片库，你可以根据demo中使用fresco库的方式拓展使用Glide4.0版本，XSnow框架中依赖Glide只是包含并不会打包到APK中去，最终的依赖是以你项目中依赖的Glide版本为准。

**Comment by DaiFalin** [comment]
@xiaoyaoyou1212 变动是有点大，有些东西单独分离了，跟V3版本使用方式有一些差别
