### ISSUE TITLE
多个baseurl情况

### ISSUE THREAD

**Issue by fangx** [xiaoyaoyou1212/XSnow#14]
作者你好，针对多个baseurl情况有没有啥好的处理~

**Comment by xiaoyaoyou1212** [comment]
目前是有支持的，默认使用全局配置的baseurl，如果单个请求有不一样的情况可以单独设置，你的具体需求是？

**Comment by fangx** [comment]
是不是每次请求都需要 ViseHttp.CONFIG().baseUrl("") 来设置一下~

**Comment by xiaoyaoyou1212** [comment]
@fangx 这个不需要的，比如POST请求调用ViseHttp.POST("").baseUrl("")设置就行

**Comment by xiaoyaoyou1212** [comment]
那个CONFIG配置是针对全局的，只在应用初始化时调用一次就行

**Comment by fangx** [comment]
好的，谢谢~
