### ISSUE TITLE
类型转换问题

### ISSUE THREAD

**Issue by robinxdroid** [xiaoyaoyou1212/XSnow#22]
ApiResultFunc中String类型需要单独处理，我看了ApiFunc中有处理，为什么ApiResultFunc中不加入处理呢，实测会引起类型转换异常，"期望String,实际是一个Object"

**Comment by xiaoyaoyou1212** [comment]
@robinxdroid 好，我处理下，谢谢提出！

**Comment by xiaoyaoyou1212** [comment]
@robinxdroid 刚看了demo中有提供返回string的调用方式，使用是没问题的

**Comment by robinxdroid** [comment]
嗯，demo是没有问题，我使用的时候出现了异常，原因现在还不太明朗

**Comment by robinxdroid** [comment]
我从这里看到了类似的问题描述与我的情况基本吻合,我是想把data转为String时出现了异常
[https://blog.csdn.net/xiangzhihong8/article/details/51863166](https://blog.csdn.net/xiangzhihong8/article/details/51863166)


例如下面Json字符串：

        {"code":1,"info":"success","results":{"id":"1","name":"hehe"}}

        results对应的应该是一个实体类，如果这个时候想把他解析为String或者List就会出现异常。

楼主有空的时候不妨用其他json数据试试

**Comment by xiaoyaoyou1212** [comment]
@robinxdroid 要实现可以，我可以在内部强制转成String，但不明白的是你这个本身就是要解析成一个实体类对象，为啥要用String来解析

**Comment by robinxdroid** [comment]
框架么，灵活多变，谁知道以后会出现什么乱七八糟的json必须要手解的情况，哈哈

**Comment by xiaoyaoyou1212** [comment]
@robinxdroid 好，这个我加上吧，万一真要这样做也能满足，谢谢提出哈！
