### ISSUE TITLE
多个 .baseUrl 的问题

### ISSUE THREAD

**Issue by dacaoyuan** [xiaoyaoyou1212/XSnow#25]
现在公司采用了，您的网络框架。请问博主，如果我想配置多个 baseUrl 怎么处理呢？现在大部分接口，都是一个baseUrl，我直接在application中配置就可以了。但是有的接口，需要另一个baseUrl，如此一来，让我不知怎么办了。麻烦博主，指教一下吧，谢谢！

**Comment by xiaoyaoyou1212** [comment]
@dacaoyuan 这个可以单独针对某个请求设置对应的baseurl的，该baseurl只会影响该请求，你可以看下代码中提供的相关方法

**Comment by dacaoyuan** [comment]
谢谢

**Comment by dacaoyuan** [comment]
解决了，谢谢
