### ISSUE TITLE
一点小小建议

### ISSUE THREAD

**Issue by 214024475** [xiaoyaoyou1212/XSnow#26]
建议使用mvp模式或者mvvm模式  然后在Application里面定义统一异常处理  现在控件一般几乎不会去findViewById直接用butterknife   网络这一块可以用开源的api来实现一个demo即可     然后重点讲一下加密请求就可以啦  上传和下载一般小型app用得不多   根据自己需求来加就ok了  暂时就这些

**Comment by xiaoyaoyou1212** [comment]
@214024475 好的，后续功能优化时加上这个需求点

**Comment by docwei2050** [comment]
没有用mvp真可惜，其实retrofit+rxjava2+mvp才是标配。。。

**Comment by GreenVegetables** [comment]
什么乱七八糟的，还整butterknife，自己玩去，此框架核心看懂了吗，还mvp，那是业务用的东西。

**Comment by KevinLium** [comment]
使用kotlin 就不用butterknife了。
mvp 那种 会增加大量额外代码。拒绝使用
