### ISSUE TITLE
多个主机地址应如何配置呢？

### ISSUE THREAD

**Issue by ydmmocoo** [xiaoyaoyou1212/XSnow#6]
如题。

**Comment by xiaoyaoyou1212** [comment]
@ydmmocoo 可以在应用初始化时使用一个全局主机地址，如果某个请求的主机地址不一样，那么可以在请求时设置baseURL，这样该请求的主机地址就会替换全局的主机地址。

**Comment by ZQiang94** [comment]
按照这种方式不是很灵活啊:see_no_evil:

**Comment by QuincySx** [comment]
首先我还不了解这个库，我也是才开始看，我说一下 Retrofit 是怎么进行多主机地址配置的:
我们一般的做法是设置 Retrofit 的 Baseurl  ,然后在 Api 接口中写 @GET("xxxxx") 等等请求接口,
如果要做换主机地址那么就在 @GET("http://xxxxxx/") 接口中写成这样，他就不会读 Baseurl  ，而是直接请求,
这样的话 我们每个主机建立一个相应的 Api 接口文件放置一个 Host 字段来存储主机地址，进行拼接然后访问，或等等之类的方法，就能灵活控制多主机请求的问题

**Comment by xiaoyaoyou1212** [comment]
@QuincySx 该库支持全局替换baseURL，也支持在单个请求中配置baseURL的，这样能避免每次都修改get()后缀中的地址
