### ISSUE TITLE
博主，找不到ApiPostRequest

### ISSUE THREAD

**Issue by AbrahamCaiJin** [xiaoyaoyou1212/XSnow#7]
ApiPostRequest这个是要自己写吗？

**Comment by xiaoyaoyou1212** [comment]
@AbrahamCaiJin 在网络拓展库netexpand中，由于没各自服务器的结构不一样，所以没法统一，只提供了思路，如果你需要用的话需要按照你服务器定义的结构拷贝过去修改下就行。
