### ISSUE TITLE
如何取消掉当前正在执行的网络请求？

### ISSUE THREAD

**Issue by ZephHe** [xiaoyaoyou1212/XSnow#8]
如题：如何取消掉当前正在执行的网络请求？

**Comment by xiaoyaoyou1212** [comment]
@TheShey 根据tag取消网络请求，你可以在网络请求时设置tag，再在需要取消的时候调用ViseHttp.cancelTag(tag);就行了

**Comment by ZephHe** [comment]
我用上的第一个请求网络的方法，报出以下异常Log：
E/ViseLog: HttpLogInterceptor.intercept(HttpLogInterceptor.java:70): <-- HTTP FAILED: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Set java.util.concurrent.ConcurrentHashMap.keySet()' on a null object reference

**Comment by xiaoyaoyou1212** [comment]
@TheShey 你这个是报了空指针错误，具体能看到是哪行代码影响的错误么

**Comment by ZephHe** [comment]
我全局搜索了源码中的ConcurrentHashMap，CookiesStore.java 中用到了 
然后我在ViseHttp.Config().setCookie(false)就不报错了,出错的时候设置的是true,请问这是为什么呢？

**Comment by xiaoyaoyou1212** [comment]
@TheShey 这个问题我后面修复下
