### ISSUE TITLE
是否应该把Retrofit从Request中抽离出来更好？

### ISSUE THREAD

**Issue by qinicy** [xiaoyaoyou1212/XSnow#9]
大概地看了2.0版本的网络模块，相对于1.0版本，2.0版本灵活度更高功能也更完善了。但在看到BaseRequest#generateLocalConfig这里，总感觉怪怪的：这意味着每一次网络请求，都会新建一个Retrofit对象，但其实每一个Retrofit的config其实是一样的（baseUrl == null时）。所以我觉得每一次新建一个Retrofit是非必要的。

**Comment by xiaoyaoyou1212** [comment]
@qinicy 这个在没设置请求头和局部配置时确实会有重复创建的问题，我后面优化下这个，你有什么好的建议么？

**Comment by qinicy** [comment]
大概想法是不在Request里内建Retrofit,创建Request时再动态获取和配置Retrofit，这就意味着这改动比较大。
